#!/usr/bin/env bash

## Initialise the project
fin start

# Download project dependencies.
fin run composer install

# Install Drupal.
fin drush site-install -y \
  --account-pass=admin \
  --site-name='Drupal Testing Workshop'

fin uli
